name: Execution Performance

on:
  workflow_dispatch:
    inputs:
      testSuite:
        type: string
        description: 'testSuite'
        required: true
        default: 'pokemonapi.PokemonApiTest'
      concurrent:
        type: string
        description: 'Quantity of users'
        required: true
        default: '10'

jobs:
  execpokemonapi:
    runs-on: ubuntu-latest
    name: Execution Performance Pokemon API
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Run Load Test
        uses: elmer-zapata-mojix-com/locust-github-action@master
        with:
          LOCUSTFILE: "locustfile.py"
          REQUIREMENTS: "requirements.txt"
          URL:  "https://pokeapi.co "
          USERS: "10"
          RATE: "5"
          RUNTIME: "10s"
          html: "report.html"

      - name: Save report
        if: ${{always()}}
        uses: actions/upload-artifact@v3.1.2
        with:
          name: gatling report
          path: ./report.html

      - name: "Publish test results"
        uses: peaceiris/actions-gh-pages@v3.7.3
        if: ${{ always() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './build/reports/gatling'
          keep_files: true
          user_name: elmer-zapata-mojix-com
          user_email: elmer.zapata@mojix.com
          publish_branch: gh_page


